[build]
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests"
watchPatterns = ["src/**"]

[deploy]
startCommand = "java -jar target/portfolio-backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/experiences"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8080"
NIXPACKS_JAVA_VERSION = "17" 